//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.About", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The concept.
        /// </summary>
        internal static string concept {
            get {
                return ResourceManager.GetString("concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streameus is participatory network that allows you to follow and create conferences in the domains you care about..
        /// </summary>
        internal static string concept_paragraph {
            get {
                return ResourceManager.GetString("concept_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As a listener, you are free to participate in all conferences of your choice, to confront your opinion, chat with other listeners and even speak alongside the speaker. If a speaker broadcasts content that interests you, you can follow in order to be kept informed of their news. To ensure the quality of the lectures, Streameus allows lecturers to set an entry price (or not). The speakers are more attentive to the quality of content they deliver and assured listeners to attend a conference match their expecta [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The EIP Epitech Innovative Project is like a graduation project done by groups of 6 people or more. It starts in the middle of the third year and ends at the end of fifth year. The goal of this innovative project is to provide a finished, durable, documented and used directly in the professional world project. The subject is free and chosen by the student, it must be original and new carrier and is subject to validation of laboratory EIP that will provide students with assistance in the form of tutoring. Th [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string eip {
            get {
                return ResourceManager.GetString("eip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Want to learn more about Streameus? You are on the right page..
        /// </summary>
        internal static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
    }
}
