//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Events", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created {1} conference(s) during this month..
        /// </summary>
        internal static string bilanCreateConfMonth {
            get {
                return ResourceManager.GetString("bilanCreateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created {1} conference(s) during this week..
        /// </summary>
        internal static string bilanCreateConfWeek {
            get {
                return ResourceManager.GetString("bilanCreateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has now {1} followers..
        /// </summary>
        internal static string bilanFollowers {
            get {
                return ResourceManager.GetString("bilanFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} start to follow {1} new people during this month..
        /// </summary>
        internal static string bilanFollowingMonth {
            get {
                return ResourceManager.GetString("bilanFollowingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} start to follow {1} new people during this week..
        /// </summary>
        internal static string bilanFollowingWeek {
            get {
                return ResourceManager.GetString("bilanFollowingWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to {1} conference(s) during this month..
        /// </summary>
        internal static string bilanParticipateConfMonth {
            get {
                return ResourceManager.GetString("bilanParticipateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to {1} conference(s) during this week.
        /// </summary>
        internal static string bilanParticipateConfWeek {
            get {
                return ResourceManager.GetString("bilanParticipateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has reached {1} reputation points..
        /// </summary>
        internal static string bilanReputation {
            get {
                return ResourceManager.GetString("bilanReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created a conference {1}..
        /// </summary>
        internal static string createConf {
            get {
                return ResourceManager.GetString("createConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gets {1} first follower !.
        /// </summary>
        internal static string FirstFollower {
            get {
                return ResourceManager.GetString("FirstFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has participated to the conference {1}..
        /// </summary>
        internal static string ParticipateConf {
            get {
                return ResourceManager.GetString("ParticipateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has rated {1} stars the conference {2}..
        /// </summary>
        internal static string RateConf {
            get {
                return ResourceManager.GetString("RateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starts to follow {1}..
        /// </summary>
        internal static string StartFollow {
            get {
                return ResourceManager.GetString("StartFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to the conference {1}..
        /// </summary>
        internal static string SuscribeConf {
            get {
                return ResourceManager.GetString("SuscribeConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has updated {1} personal description {2}..
        /// </summary>
        internal static string UpdateMsgPerso {
            get {
                return ResourceManager.GetString("UpdateMsgPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has updated the field {1} for {2}..
        /// </summary>
        internal static string UpdateParameter {
            get {
                return ResourceManager.GetString("UpdateParameter", resourceCulture);
            }
        }
    }
}
