//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streameus.App_GlobalResources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has created {1} conference(s) during this month..
        /// </summary>
        public static string BilanCreateConfMonth {
            get {
                return ResourceManager.GetString("BilanCreateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has created {1} conference(s) during this week..
        /// </summary>
        public static string BilanCreateConfWeek {
            get {
                return ResourceManager.GetString("BilanCreateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has now {1} followers..
        /// </summary>
        public static string BilanFollowers {
            get {
                return ResourceManager.GetString("BilanFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} start to follow {1} new people during this month..
        /// </summary>
        public static string BilanFollowingMonth {
            get {
                return ResourceManager.GetString("BilanFollowingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} start to follow {1} new people during this week..
        /// </summary>
        public static string BilanFollowingWeek {
            get {
                return ResourceManager.GetString("BilanFollowingWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has signed up to {1} conference(s) during this month..
        /// </summary>
        public static string BilanParticipateConfMonth {
            get {
                return ResourceManager.GetString("BilanParticipateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has signed up to {1} conference(s) during this week.
        /// </summary>
        public static string BilanParticipateConfWeek {
            get {
                return ResourceManager.GetString("BilanParticipateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has reached {1} reputation points..
        /// </summary>
        public static string BilanReputation {
            get {
                return ResourceManager.GetString("BilanReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has changed {1} photo {2}..
        /// </summary>
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has modified the date of the conference {1}, it will start the {2}..
        /// </summary>
        public static string ConfDate {
            get {
                return ResourceManager.GetString("ConfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has changed the description of the conference {1}..
        /// </summary>
        public static string ConfDescription {
            get {
                return ResourceManager.GetString("ConfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The conference {0} of {1} is finished !.
        /// </summary>
        public static string ConferenceEnd {
            get {
                return ResourceManager.GetString("ConferenceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The conference {0} of {1} starts now !.
        /// </summary>
        public static string ConferenceStart {
            get {
                return ResourceManager.GetString("ConferenceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has modified the time of the conference {1}, it will start at {2}..
        /// </summary>
        public static string ConfTime {
            get {
                return ResourceManager.GetString("ConfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has changed the title of the conference {1}..
        /// </summary>
        public static string ConfTitle {
            get {
                return ResourceManager.GetString("ConfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has planified the conference {1} the {2} at {3}..
        /// </summary>
        public static string CreateConf {
            get {
                return ResourceManager.GetString("CreateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} gets {1} first follower !.
        /// </summary>
        public static string FirstFollower {
            get {
                return ResourceManager.GetString("FirstFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has participated to the conference {1}..
        /// </summary>
        public static string ParticipateConf {
            get {
                return ResourceManager.GetString("ParticipateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has rated {1} stars the conference {2}..
        /// </summary>
        public static string RateConf {
            get {
                return ResourceManager.GetString("RateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} recommand the conference {1}..
        /// </summary>
        public static string Recommand {
            get {
                return ResourceManager.GetString("Recommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a shared the conference {1} of {2} which starts {3} at {4}.
        /// </summary>
        public static string ShareConf {
            get {
                return ResourceManager.GetString("ShareConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} starts to follow {1}..
        /// </summary>
        public static string StartFollow {
            get {
                return ResourceManager.GetString("StartFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has signed up to the conference {1}..
        /// </summary>
        public static string SuscribeConf {
            get {
                return ResourceManager.GetString("SuscribeConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has updated {1} personal description {2}..
        /// </summary>
        public static string UpdateMsgPerso {
            get {
                return ResourceManager.GetString("UpdateMsgPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has updated the field {1} for {2}..
        /// </summary>
        public static string UpdateParameter {
            get {
                return ResourceManager.GetString("UpdateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has invited you to the conference {1} of {2}..
        /// </summary>
        public static string UserInvitation {
            get {
                return ResourceManager.GetString("UserInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} will participate at the conference {1} the {2} at {3}.
        /// </summary>
        public static string WillParticipateConf {
            get {
                return ResourceManager.GetString("WillParticipateConf", resourceCulture);
            }
        }
    }
}
