//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streameus.App_GlobalResources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created {1} conference(s) during this month..
        /// </summary>
        public static string BilanCreateConfMonth {
            get {
                return ResourceManager.GetString("BilanCreateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created {1} conference(s) during this week..
        /// </summary>
        public static string BilanCreateConfWeek {
            get {
                return ResourceManager.GetString("BilanCreateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has now {1} followers..
        /// </summary>
        public static string BilanFollowers {
            get {
                return ResourceManager.GetString("BilanFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} start to follow {1} new people during this month..
        /// </summary>
        public static string BilanFollowingMonth {
            get {
                return ResourceManager.GetString("BilanFollowingMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} start to follow {1} new people during this week..
        /// </summary>
        public static string BilanFollowingWeek {
            get {
                return ResourceManager.GetString("BilanFollowingWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to {1} conference(s) during this month..
        /// </summary>
        public static string BilanParticipateConfMonth {
            get {
                return ResourceManager.GetString("BilanParticipateConfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to {1} conference(s) during this week.
        /// </summary>
        public static string BilanParticipateConfWeek {
            get {
                return ResourceManager.GetString("BilanParticipateConfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has reached {1} reputation points..
        /// </summary>
        public static string BilanReputation {
            get {
                return ResourceManager.GetString("BilanReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created a conference {1}..
        /// </summary>
        public static string CreateConf {
            get {
                return ResourceManager.GetString("CreateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gets {1} first follower !.
        /// </summary>
        public static string FirstFollower {
            get {
                return ResourceManager.GetString("FirstFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has participated to the conference {1}..
        /// </summary>
        public static string ParticipateConf {
            get {
                return ResourceManager.GetString("ParticipateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has rated {1} stars the conference {2}..
        /// </summary>
        public static string RateConf {
            get {
                return ResourceManager.GetString("RateConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starts to follow {1}..
        /// </summary>
        public static string StartFollow {
            get {
                return ResourceManager.GetString("StartFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has signed up to the conference {1}..
        /// </summary>
        public static string SuscribeConf {
            get {
                return ResourceManager.GetString("SuscribeConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has updated {1} personal description {2}..
        /// </summary>
        public static string UpdateMsgPerso {
            get {
                return ResourceManager.GetString("UpdateMsgPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has updated the field {1} for {2}..
        /// </summary>
        public static string UpdateParameter {
            get {
                return ResourceManager.GetString("UpdateParameter", resourceCulture);
            }
        }
    }
}
