//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Faq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Faq() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Faq", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profits of your conference will be sent to the Paypal account you have specified. The payment will be
        ///made within two days..
        /// </summary>
        internal static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, all your information stored on our databases are strictly protected. In addition, some sensitive
        ///information such as your password are encrypted using mathematical algorithms..
        /// </summary>
        internal static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A cookie is a small text file stored by your browser, which allows us to retain information between
        ///web pages and browsing sessions. Streameus uses severals of cookies. They allow us, for example, to
        ///keep you authenticated whenever you change page.
        ///Cookies are only text, which is always confidential and in most cases encrypted. Streameus never
        ///keep any personal data in a cookie..
        /// </summary>
        internal static string a11 {
            get {
                return ResourceManager.GetString("a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Following someone allows you to be kept informed of its activities and thus to be notified when this
        ///person attended a conference or when it will hold one.
        ///Anyone can follow you, however, is up to you to decide what the people who follow you can see. To
        ///set your confidentiality parameters simply go to &quot;My Account&quot; → &quot;My confidentiality Settings&quot;..
        /// </summary>
        internal static string a12 {
            get {
                return ResourceManager.GetString("a12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, we have created three applications that can be used from Windows Phone, Android and iOS.
        ///You can find these applications from the stores of those platforms..
        /// </summary>
        internal static string a13 {
            get {
                return ResourceManager.GetString("a13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no limit on earnings. The money raised through your conference depends only on the
        ///number of users present in your conference and the price you previously set for it..
        /// </summary>
        internal static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can fund your account by visiting the « My Account » space, and filling in your credit card or your
        ///Paypal account. Your balance is credited in real time..
        /// </summary>
        internal static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can create a Streameus account, or login directly on the website with your Facebook, Twitter or
        ///Google Plus account. Registering takes only a few minutes, simply fill out the form that appears after
        ///you click the button &quot;Sign me&quot; on the homepage..
        /// </summary>
        internal static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To recover your password, go to the « login » page then click on the link &quot;Forgot your password&quot;
        ///below the login form. After entering your username or your e-mail, you will receive an e-mail stating
        ///the procedure to follow in order to change your password..
        /// </summary>
        internal static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You encounter difficulties, or you have spotted a bug? You can contact us by clicking on the « contact
        ///us » link present on the footer of the website..
        /// </summary>
        internal static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register, interact with other users and create a conference on Streameus is completely free.
        ///Nevertheless, some conferences are not free to attend so you will have to pay the specified price..
        /// </summary>
        internal static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streameus is composed of a team of 8 people. The project was born in the Epitech School in Lyon
        ///under the Epitech Innovative Projects (EIP). For more information, you can go to the page &quot;About&quot; →
        ///&quot;The team&quot;..
        /// </summary>
        internal static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, you can delete your account from in “My Account&quot; → &quot;Delete my account&quot;. However, data such
        ///conferences may persist because it they are shared with other users..
        /// </summary>
        internal static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequently Asked Questions.
        /// </summary>
        internal static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How am I remunerated?.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is my information is secure?.
        /// </summary>
        internal static string q10 {
            get {
                return ResourceManager.GetString("q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What are Cookies? And what do you do with it?.
        /// </summary>
        internal static string q11 {
            get {
                return ResourceManager.GetString("q11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is following someone? Who can follow me?.
        /// </summary>
        internal static string q12 {
            get {
                return ResourceManager.GetString("q12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can I use Streameus from my mobile?.
        /// </summary>
        internal static string q13 {
            get {
                return ResourceManager.GetString("q13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How high can I be paid?.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I would like to attend a paying conference, how should I do?.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How to register? Does it take time?.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I forgot my password?.
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How can I contact you?.
        /// </summary>
        internal static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is it free?.
        /// </summary>
        internal static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who is behind Streameus?.
        /// </summary>
        internal static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can I delete my account?.
        /// </summary>
        internal static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
    }
}
