//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.Models
{
    //prevent documentation warning for autogenerated code
    #pragma warning disable 1591
    
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceParameters
    {
        public ConferenceParameters()
        {
            this.Price = 0D;
            this.FreeTime = 0;
            this.CanAskQuestions = true;
            this.CansAskVoiceQuestions = true;
            this.Visibility = true;
            this.FreeUsers = new HashSet<User>();
            this.Intervenants = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public double Price { get; set; }
        public int FreeTime { get; set; }
        public bool CanAskQuestions { get; set; }
        public bool CansAskVoiceQuestions { get; set; }
        public bool Visibility { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual ICollection<User> FreeUsers { get; set; }
        public virtual ICollection<User> Intervenants { get; set; }
    }
    #pragma warning restore 1591
}
