//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public Conference()
        {
            this.ScheduledDuration = 60;
            this.Members = new HashSet<User>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Streameus.Enums.DataBaseEnums.ConfStatus Status { get; set; }
        public System.DateTime Time { get; set; }
        public int ScheduledDuration { get; set; }
        public int FinalDuration { get; set; }
    
        public virtual User Owner { get; set; }
        public virtual ICollection<User> Members { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ConferenceParameters ConferenceParameter { get; set; }
    }
}
