//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.Models
{
    //prevent documentation warning for autogenerated code
    #pragma warning disable 1591
    
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public bool Visibility { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User Author { get; set; }
    }
    #pragma warning restore 1591
}
