#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.DataAbstractionLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Streameus.Models;
    
    public partial class StreameusContainer : DbContext
    {
        public StreameusContainer()
            : base("name=StreameusContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ConferenceParameters> ConferenceParameters { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
#pragma warning restore 1591

