#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.DataAbstractionLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Models;
    
    public partial class StreameusContainer : DbContext
    {
        public StreameusContainer()
            : base("name=StreameusContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ConferenceParameters> ConferenceParameters { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}

#pragma warning restore 1591