//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streameus.Models
{
    //prevent documentation warning for autogenerated code
    #pragma warning disable 1591
    
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Language = "FR-fr";
            this.EmailVisibility = true;
            this.FirstName = "";
            this.FirstNameVisibility = true;
            this.LastName = "";
            this.LastNameVisibility = true;
            this.PicturePath = "";
            this.GenderVisibility = true;
            this.Reputation = 0;
            this.AbonnementsVisibility = true;
            this.Phone = "";
            this.Address = "";
            this.City = "";
            this.Country = "";
            this.Website = "";
            this.Profession = "";
            this.Description = "";
            this.ConferencesCreated = new HashSet<Conference>();
            this.Conferences = new HashSet<Conference>();
            this.Posts = new HashSet<Post>();
            this.Abonnements = new HashSet<User>();
            this.Followers = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Pseudo { get; set; }
        public string Language { get; set; }
        public string Email { get; set; }
        public bool EmailVisibility { get; set; }
        public string FirstName { get; set; }
        public bool FirstNameVisibility { get; set; }
        public string LastName { get; set; }
        public bool LastNameVisibility { get; set; }
        public string PicturePath { get; set; }
        public Nullable<bool> Gender { get; set; }
        public bool GenderVisibility { get; set; }
        public int Reputation { get; set; }
        public bool AbonnementsVisibility { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public string Profession { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Conference> ConferencesCreated { get; set; }
        public virtual ICollection<Conference> Conferences { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<User> Abonnements { get; set; }
        public virtual ICollection<User> Followers { get; set; }
        public virtual Parameters Parameter { get; set; }
    }
    #pragma warning restore 1591
}
